apiVersion: skaffold/v1beta9
kind: Config
build:
  artifacts:
  - image: gcr.io/cloud-build-1/helloworld
    context: .
  tagPolicy:
    sha256: {}
deploy:
  kubectl:
    manifests:
    - kubernetes-manifests/**
profiles:
- name: cloudbuild
  build:
    googleCloudBuild:
      projectId: cloud-build-1
